build:
    environment:
        php: '8.2'

    tests:
        override:
            - true

build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 10)'

checks:
    php:
        code_rating: true
        duplication: true
